### PR TITLE
Asserts existence of required environment variables

### PR DESCRIPTION
**Pull request by augustohp**
I've changed quite some things, which might be overwhelming. I am sorry for that, I just can't get a hold of myself.

Changes are explained on commit messages in more detail, but this should solve assertion of environment variables along with keeping previous behavior unchanged.

PS: Thanks for sharing the code. ♥️

### CODE REVIEW

**Comment by natfarleydev** [comment]
Thanks, this looks like good work. 

I noticed that you changed `habash getidoftask` to `habash id`. Is there a reason for this? I'd prefer to keep `getidoftask` if possible (maybe add a warning that it will be deprecated in the future?) rather than cause breaking changes.

(I haven't had a chance to test the code yet so `habash getidoftask` may still work, feel free to correct me.)

**Comment by augustohp** [comment]
> I noticed that you changed `habash getidoftask` to `habash id`. Is there a reason for this?

It is shorter and difficult to read words together without any form of separation between them.

> I'd prefer to keep `getidoftask` if possible

It [still works][1], just not documented.

[1]: https://github.com/nasfarley88/habash/pull/7/files#diff-6d61a8c60226268395e99368bceca412R111

**Comment by natfarleydev** [comment]
I agree, `getidoftask` is cumbersome but I think `id` is a little too vague. Maybe `get-task-id` or something? 

I also noticed `createhabit` is now `habit` etc.. Descriptive names are better than short names here, I'd prefer `create-habit`or similar if readability is what you're after?

**Comment by natfarleydev** [comment]
Merging for now, we can figure out command names later.

**Pull request merged**
